name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push backend image
        working-directory: ./api
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-backend:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-backend:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-backend:$TIMESTAMP
      
      - name: Build and push frontend image
        working-directory: ./front-end-nextjs
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file Dockerfile \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-frontend:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-frontend:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-qr-code-frontend:$TIMESTAMP
