name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image of backend
        run: docker build . --file api/Dockerfile --tag devops-qr-code-backend:$(date +%s)
      - name: Build the Docker image of frontend
        run: docker build . --file front-end-nextjs/Dockerfile --tag devops-qr-code-frontend:$(date +%s)
