name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image of backend
        run: docker build . --file Dockerfile --tag devops-qr-code-backend:$(date +%s)
        working-directory: ./api
      - name: Build the Docker image of frontend
        run: docker build . --file Dockerfile --tag devops-qr-code-frontend:$(date +%s)
        working-directory: ./front-end-nextjs
